server:
  port: 8087
  servlet:
    context-path: /
spring:
  datasource:
    username: ishell
    password: 密码
    url: jdbc:mysql://IP:端口/ishell?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 50000
  mail:
    host: smtp.qq.com
    username: 邮箱
    password: 授权码
    default-encoding: UTF-8
    protocol: smtp
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
            ssl:
              enable: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  redis:
    host: 101.133.164.208
    port: Redis端口
    password: Redis密码
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: 5000
        max-idle: 8
        min-idle: 0
    timeout: 3000
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
    com.ishell.mapper: debug
